# Periodic APAP Dosing Model - Second Trimester
# Simulates repeated acetaminophen exposure at weeks 14, 18, and 22
name: myelination_periodic

# Name of the model file (SBML format)
model: APAP_Periodic_Dosing_Model.xml

# Solver configuration
solver: dormand_prince_54
stepSize: 1  # 1 hour resolution to capture dosing dynamics
duration: 2688  # 16 weeks (weeks 12-28 = 112 days * 24 hours)

## Initial conditions
inputs:
    # Start with no APAP (dosing will be added by model rules)
    APAP_maternal: 0.0
    APAP_placenta: 0.0
    APAP_fetal: 0.0
    NAPQI: 0.0
    
    # Normal second trimester hormones
    Testosterone: 300.0
    T_effective: 50.0
    
    # Oxidative stress markers
    CYP2E1: 1.0
    GSH: 100.0
    GSSG: 10.0
    ROS: 5.0
    
    # Cell populations
    OPC: 5000.0
    OL_immature: 500.0
    OL_mature: 200.0
    
    # Supporting systems
    Folate: 40.0
    SAM: 20.0
    
    # Start at week 12
    gestational_week: 12.0
    critical_period_1: 3.5
    dosing_active: 0.0
    
    # Dosing parameters
    dose_amount: 2.0  # Standard therapeutic dose
    dose_interval: 6.0  # Every 6 hours
    
    # Rate parameters
    k_placental_transfer: 0.05
    k_fetal_clearance: 0.02
    k_maternal_clearance: 0.15
    k_cyp2e1_activity: 0.05
    T_baseline: 300.0
    T_production_rate: 5.0
    androgen_disruption_rate: 0.1
    opc_proliferation_rate: 0.002
    ol_differentiation_rate: 0.001
    ros_generation_rate: 0.05
    gsh_regeneration_rate: 0.1
    antioxidant_capacity: 1.0

# Charts showing periodic exposure effects
charts:
    - filename: apap_periodic_exposure.png
      type: line
      title: "Periodic APAP Exposure - Second Trimester"
      axisParamX: time
      axisLabelX: "Hours from Week 12"
      axisLabelY: "Concentration (uM)"
      series:
        - param: APAP_maternal
        - param: APAP_fetal
        - param: NAPQI
    
    - filename: testosterone_periodic.png
      type: line
      title: "Testosterone with Periodic Disruption"
      axisParamX: time
      axisLabelX: "Hours from Week 12"
      axisLabelY: "Level (ng/dL)"
      series:
        - param: Testosterone
        - param: T_effective
        - param: dosing_active
    
    - filename: oxidative_periodic.png
      type: line
      title: "Oxidative Stress - Periodic Exposure"
      axisParamX: time
      axisLabelX: "Hours from Week 12"
      axisLabelY: "Level (AU)"
      series:
        - param: ROS
        - param: GSH
        - param: GSSG
    
    - filename: gestational_progress.png
      type: line
      title: "Gestational Week and Critical Period"
      axisParamX: time
      axisLabelX: "Hours"
      axisLabelY: "Week / Multiplier"
      series:
        - param: gestational_week
        - param: critical_period_1