# 40-Week Myelination Model - Focus on core working dynamics
name: myelination_40weeks

# Name of the model file (SBML format)
model: APAP_Myelination_Model.xml

# Solver configuration
solver: runge_kutta
stepSize: 24  # 1 day steps for long simulation
duration: 6720  # 40 weeks (280 days * 24 hours)

## Initial conditions - focus on working components
inputs:
    # APAP exposure - periodic dosing simulation
    APAP_maternal: 5.0  # Lower initial dose
    APAP_placenta: 0.0
    APAP_fetal: 0.0
    NAPQI: 0.0
    
    # Endocrine system
    Testosterone: 450.0  # Peak fetal testosterone
    T_effective: 0.0
    
    # Cell populations
    OPC: 1000.0
    OL_immature: 0.0
    OL_mature: 0.0
    
    # Oxidative stress markers - initialize properly
    CYP2E1: 1.0  # Need this for NAPQI generation
    GSH: 100.0
    GSSG: 0.0
    ROS: 10.0  # Small initial value
    
    # Supporting systems
    Folate: 50.0
    SAM: 25.0
    
    # Time tracking
    gestational_week: 12.0
    critical_period_1: 1.0
    
    # Key rates - enable core dynamics
    k_placental_transfer: 0.1  # Slower transfer for sustained exposure
    k_fetal_clearance: 0.05  # Slower clearance
    k_cyp2e1_activity: 0.2
    opc_proliferation_rate: 0.01  # Enable slow growth
    ol_differentiation_rate: 0.005  # Enable differentiation
    ros_generation_rate: 0.3
    androgen_disruption_rate: 0.5
    
# Focus on 3 core working charts
charts:
    - filename: apap_exposure_40weeks.png
      type: line
      title: "APAP Exposure Levels"
      axisParamX: time
      axisLabelX: "Gestational Age (hours)"
      axisLabelY: "Concentration (uM)"
      series:
        - param: APAP_maternal
        - param: APAP_placenta
        - param: APAP_fetal
    
    - filename: oxidative_stress_40weeks.png
      type: line
      title: "Oxidative Stress Markers"
      axisParamX: time
      axisLabelX: "Gestational Age (hours)"
      axisLabelY: "Level (AU)"
      series:
        - param: ROS
        - param: GSH
        - param: GSSG
    
    - filename: testosterone_disruption_40weeks.png
      type: line
      title: "Testosterone and Critical Periods"
      axisParamX: time
      axisLabelX: "Gestational Age (hours)"
      axisLabelY: "Testosterone Level (AU)"
      series:
        - param: Testosterone
        - param: T_effective
        - param: critical_period_1